name: sportify_amateur
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  http: ^1.0.0        # Comunicación HTTP con el backend en NestJS
  flutter_bloc: ^8.1.2  # Opcional, para manejar el estado de la app
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^7.0.0
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.1.0
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.65.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icono_1.png"
flutter:
  uses-material-design: true
