// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNuDnOFPaijaIEStWebsY5i_yD_GVYORg',
    appId: '1:489565755634:android:8c4e594a6514c44afd586b',
    messagingSenderId: '489565755634',
    projectId: 'sportify-amateur-dev',
    storageBucket: 'sportify-amateur-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAez82BIutAhAlz8wz9zdLTe2mkisxJ-_A',
    appId: '1:489565755634:ios:a4c4a80aeb8542ccfd586b',
    messagingSenderId: '489565755634',
    projectId: 'sportify-amateur-dev',
    storageBucket: 'sportify-amateur-dev.firebasestorage.app',
    iosBundleId: 'com.example.sportifyAmateur',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgDBeYseOkjDTtyYzx4UGmMcWhDiiavs4',
    appId: '1:489565755634:web:2afb8876385e4e83fd586b',
    messagingSenderId: '489565755634',
    projectId: 'sportify-amateur-dev',
    authDomain: 'sportify-amateur-dev.firebaseapp.com',
    storageBucket: 'sportify-amateur-dev.firebasestorage.app',
    measurementId: 'G-3RME3PF7NT',
  );

}